// Code generated by "stringer -type=Armor -trimprefix=Armor"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArmorEmpty-0]
	_ = x[ArmorAmberCard-1]
	_ = x[ArmorDiceBrace-2]
	_ = x[ArmorPinkRibbon-3]
	_ = x[ArmorWhiteRibbon-4]
	_ = x[ArmorIronShackle-5]
	_ = x[ArmorMouseToken-6]
	_ = x[ArmorJevilstail-7]
	_ = x[ArmorSilverCard-8]
	_ = x[ArmorTwinRibbon-9]
	_ = x[ArmorGlowWrist-10]
	_ = x[ArmorChainMail-11]
	_ = x[ArmorBShotBowtie-12]
	_ = x[ArmorSpikeBand-13]
	_ = x[ArmorSilverWatch-14]
	_ = x[ArmorTensionBow-15]
	_ = x[ArmorMannequin-16]
	_ = x[ArmorDarkGoldBand-17]
	_ = x[ArmorSkyMantle-18]
	_ = x[ArmorSpikeShackle-19]
	_ = x[ArmorFrayedBowtie-20]
	_ = x[ArmorDealmaker-21]
	_ = x[ArmorRoyalPin-22]
	_ = x[ArmorShadowMantle-23]
	_ = x[ArmorLodeStone-24]
	_ = x[ArmorGingerGuard-25]
	_ = x[ArmorBlueRibbon-26]
	_ = x[ArmorTennaTie-27]
}

const _Armor_name = "EmptyAmberCardDiceBracePinkRibbonWhiteRibbonIronShackleMouseTokenJevilstailSilverCardTwinRibbonGlowWristChainMailBShotBowtieSpikeBandSilverWatchTensionBowMannequinDarkGoldBandSkyMantleSpikeShackleFrayedBowtieDealmakerRoyalPinShadowMantleLodeStoneGingerGuardBlueRibbonTennaTie"

var _Armor_index = [...]uint16{0, 5, 14, 23, 33, 44, 55, 65, 75, 85, 95, 104, 113, 124, 133, 144, 154, 163, 175, 184, 196, 208, 217, 225, 237, 246, 257, 267, 275}

func (i Armor) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Armor_index)-1 {
		return "Armor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Armor_name[_Armor_index[idx]:_Armor_index[idx+1]]
}
