// Code generated by "stringer -type=Character -trimprefix=Character"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CharacterEmpty-0]
	_ = x[CharacterKris-1]
	_ = x[CharacterSusie-2]
	_ = x[CharacterRalsei-3]
	_ = x[CharacterNoelle-4]
}

const _Character_name = "EmptyKrisSusieRalseiNoelle"

var _Character_index = [...]uint8{0, 5, 9, 14, 20, 26}

func (i Character) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Character_index)-1 {
		return "Character(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Character_name[_Character_index[idx]:_Character_index[idx+1]]
}
