// Code generated by "stringer -type=Element -trimprefix=Element"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ElementEmpty-0]
}

const _Element_name = "Empty"

var _Element_index = [...]uint8{0, 5}

func (i Element) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Element_index)-1 {
		return "Element(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Element_name[_Element_index[idx]:_Element_index[idx+1]]
}
