// Code generated by "stringer -type=Item -trimprefix=Item"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemEmpty-0]
	_ = x[ItemDarkerCandy-1]
	_ = x[ItemReviveMint-2]
	_ = x[ItemGlowshard-3]
	_ = x[ItemManual-4]
	_ = x[ItemBrokenCake-5]
	_ = x[ItemTopCake-6]
	_ = x[ItemSpinCake-7]
	_ = x[ItemDarkburger-8]
	_ = x[ItemLancerCookie-9]
	_ = x[ItemGigaSalad-10]
	_ = x[ItemClubswich-11]
	_ = x[ItemHeartsDonut-12]
	_ = x[ItemChocDiamond-13]
	_ = x[ItemFavSandwich-14]
	_ = x[ItemRouxlsRoux-15]
	_ = x[ItemCDBagel-16]
	_ = x[ItemMannequin-17]
	_ = x[ItemRottenTea-18]
	_ = x[ItemRottenTea19-19]
	_ = x[ItemRottenTea20-20]
	_ = x[ItemRottenTea21-21]
	_ = x[ItemDDBurger-22]
	_ = x[ItemLightCandy-23]
	_ = x[ItemButJuice-24]
	_ = x[ItemSpagettiCode-25]
	_ = x[ItemJavaCookie-26]
	_ = x[ItemTensionBit-27]
	_ = x[ItemTensionGem-28]
	_ = x[ItemTensionMax-29]
	_ = x[ItemReviveDust-30]
	_ = x[ItemReviveBrite-31]
	_ = x[ItemSPoison-32]
	_ = x[ItemDogDollar-33]
	_ = x[ItemTVDinner-34]
	_ = x[ItemPipis-35]
	_ = x[ItemFlatSoda-36]
	_ = x[ItemTVSlop-37]
	_ = x[ItemExecBuffet-38]
	_ = x[ItemDeluxeDinner-39]
	_ = x[ItemPunchBowl-40]
	_ = x[ItemFlavigne-41]
	_ = x[ItemGreenTea-42]
	_ = x[ItemOrangeJuice-43]
}

const _Item_name = "EmptyDarkerCandyReviveMintGlowshardManualBrokenCakeTopCakeSpinCakeDarkburgerLancerCookieGigaSaladClubswichHeartsDonutChocDiamondFavSandwichRouxlsRouxCDBagelMannequinRottenTeaRottenTea19RottenTea20RottenTea21DDBurgerLightCandyButJuiceSpagettiCodeJavaCookieTensionBitTensionGemTensionMaxReviveDustReviveBriteSPoisonDogDollarTVDinnerPipisFlatSodaTVSlopExecBuffetDeluxeDinnerPunchBowlFlavigneGreenTeaOrangeJuice"

var _Item_index = [...]uint16{0, 5, 16, 26, 35, 41, 51, 58, 66, 76, 88, 97, 106, 117, 128, 139, 149, 156, 165, 174, 185, 196, 207, 215, 225, 233, 245, 255, 265, 275, 285, 295, 306, 313, 322, 330, 335, 343, 349, 359, 371, 380, 388, 396, 407}

func (i Item) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Item_index)-1 {
		return "Item(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Item_name[_Item_index[idx]:_Item_index[idx+1]]
}
