// Code generated by "stringer -type=KeyItem -trimprefix=KeyItem"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyItemEmpty-0]
	_ = x[KeyItemPhone-1]
	_ = x[KeyItemEgg-2]
	_ = x[KeyItemBrokenCake-3]
	_ = x[KeyItemBrokenKeyA-4]
	_ = x[KeyItemDoorKey-5]
	_ = x[KeyItemBrokenKeyB-6]
	_ = x[KeyItemBrokenKeyC-7]
	_ = x[KeyItemLancer-8]
	_ = x[KeyItemRouxlsKaard-9]
	_ = x[KeyItemEmptyDisk-10]
	_ = x[KeyItemLoadedDisk-11]
	_ = x[KeyItemKeyGen-12]
	_ = x[KeyItemShadowCrystal-13]
	_ = x[KeyItemStarwalker-14]
	_ = x[KeyItemPureCrystal-15]
	_ = x[KeyItemOddController-16]
	_ = x[KeyItemBackstagePass-17]
	_ = x[KeyItemTripTicket-18]
	_ = x[KeyItemLancerCon-19]
	_ = x[KeyItemScissors-20]
	_ = x[KeyItemYellowShred-21]
	_ = x[KeyItemBootOil-22]
	_ = x[KeyItemRedSplatter-23]
	_ = x[KeyItemBromideR-24]
	_ = x[KeyItemPetalFeather-25]
	_ = x[KeyItemPerpBook-26]
	_ = x[KeyItemBlueString-27]
	_ = x[KeyItemTrainPlan-28]
	_ = x[KeyItemYellowKey-29]
	_ = x[KeyItemSheetMusic-30]
	_ = x[KeyItemClaimbClaws-31]
	_ = x[KeyItemMysteryKey-32]
	_ = x[KeyItemBromideF-33]
}

const _KeyItem_name = "EmptyPhoneEggBrokenCakeBrokenKeyADoorKeyBrokenKeyBBrokenKeyCLancerRouxlsKaardEmptyDiskLoadedDiskKeyGenShadowCrystalStarwalkerPureCrystalOddControllerBackstagePassTripTicketLancerConScissorsYellowShredBootOilRedSplatterBromideRPetalFeatherPerpBookBlueStringTrainPlanYellowKeySheetMusicClaimbClawsMysteryKeyBromideF"

var _KeyItem_index = [...]uint16{0, 5, 10, 13, 23, 33, 40, 50, 60, 66, 77, 86, 96, 102, 115, 125, 136, 149, 162, 172, 181, 189, 200, 207, 218, 226, 238, 246, 256, 265, 274, 284, 295, 305, 313}

func (i KeyItem) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_KeyItem_index)-1 {
		return "KeyItem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyItem_name[_KeyItem_index[idx]:_KeyItem_index[idx+1]]
}
