// Code generated by "stringer -type=LItem -trimprefix=LItem"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LItemEmpty-0]
	_ = x[LItemHotChocolate-1]
	_ = x[LItemPencil-2]
	_ = x[LItemBandage-3]
	_ = x[LItemBouquet-4]
	_ = x[LItemBallOfJunk-5]
	_ = x[LItemHalloweenPencil-6]
	_ = x[LItemLuckyPencil-7]
	_ = x[LItemEgg-8]
	_ = x[LItemCards-9]
	_ = x[LItemBoxOfHeartCandy-10]
	_ = x[LItemGlass-11]
	_ = x[LItemEraser-12]
	_ = x[LItemMechPencil-13]
	_ = x[LItemWristwatch-14]
	_ = x[LItemHolidayPencil-15]
	_ = x[LItemCactusNeedle-16]
	_ = x[LItemBlackShard-17]
	_ = x[LItemQuillPen-18]
	_ = x[LItemHoneyToast-19]
	_ = x[LItemBread-20]
	_ = x[LItemSeeds-21]
	_ = x[LItemPencil2-22]
	_ = x[LItemPetal-23]
}

const _LItem_name = "EmptyHotChocolatePencilBandageBouquetBallOfJunkHalloweenPencilLuckyPencilEggCardsBoxOfHeartCandyGlassEraserMechPencilWristwatchHolidayPencilCactusNeedleBlackShardQuillPenHoneyToastBreadSeedsPencil2Petal"

var _LItem_index = [...]uint8{0, 5, 17, 23, 30, 37, 47, 62, 73, 76, 81, 96, 101, 107, 117, 127, 140, 152, 162, 170, 180, 185, 190, 197, 202}

func (i LItem) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LItem_index)-1 {
		return "LItem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LItem_name[_LItem_index[idx]:_LItem_index[idx+1]]
}
