// Code generated by "stringer -type=Phone -trimprefix=Phone"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PhoneEmpty-0]
}

const _Phone_name = "Empty"

var _Phone_index = [...]uint8{0, 5}

func (i Phone) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Phone_index)-1 {
		return "Phone(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phone_name[_Phone_index[idx]:_Phone_index[idx+1]]
}
