// Code generated by "stringer -type=SpellTarget -trimprefix=SpellTarget"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpellTargetAll-0]
	_ = x[SpellTargetAlly-1]
	_ = x[SpellTargetEnemy-2]
}

const _SpellTarget_name = "AllAllyEnemy"

var _SpellTarget_index = [...]uint8{0, 3, 7, 12}

func (i SpellTarget) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SpellTarget_index)-1 {
		return "SpellTarget(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SpellTarget_name[_SpellTarget_index[idx]:_SpellTarget_index[idx+1]]
}
