// Code generated by "stringer -type=Spell -trimprefix=Spell"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpellEmpty-0]
	_ = x[SpellRudeSword-1]
	_ = x[SpellHealPlayer-2]
	_ = x[SpellPacify-3]
	_ = x[SpellRudeBuster-4]
	_ = x[SpellRedBuster-5]
	_ = x[SpellDualHeal-6]
	_ = x[SpellACT-7]
	_ = x[SpellSleepMist-8]
	_ = x[SpellIceShock-9]
	_ = x[SpellSnowGrave-10]
	_ = x[SpellHeal-11]
	_ = x[SpellReviveSong-12]
	_ = x[SpellScythemare-13]
}

const _Spell_name = "EmptyRudeSwordHealPlayerPacifyRudeBusterRedBusterDualHealACTSleepMistIceShockSnowGraveHealReviveSongScythemare"

var _Spell_index = [...]uint8{0, 5, 14, 24, 30, 40, 49, 57, 60, 69, 77, 86, 90, 100, 110}

func (i Spell) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Spell_index)-1 {
		return "Spell(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Spell_name[_Spell_index[idx]:_Spell_index[idx+1]]
}
