// Code generated by "stringer -type=Weapon -trimprefix=Weapon"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponEmpty-0]
	_ = x[WeaponWoodBlade-1]
	_ = x[WeaponManeAx-2]
	_ = x[WeaponRedScarf-3]
	_ = x[WeaponEverybodyWeapon-4]
	_ = x[WeaponSpookysword-5]
	_ = x[WeaponBraveAx-6]
	_ = x[WeaponDevilsknife-7]
	_ = x[WeaponTrefoil-8]
	_ = x[WeaponRagger-9]
	_ = x[WeaponDaintyScarf-10]
	_ = x[WeaponTwistedSwd-11]
	_ = x[WeaponSnowRing-12]
	_ = x[WeaponThornRing-13]
	_ = x[WeaponBounceBlade-14]
	_ = x[WeaponCheerScarf-15]
	_ = x[WeaponMechaSaber-16]
	_ = x[WeaponAutoAxe-17]
	_ = x[WeaponFiberScarf-18]
	_ = x[WeaponRagger2-19]
	_ = x[WeaponBrokenSwd-20]
	_ = x[WeaponPuppetScarf-21]
	_ = x[WeaponFreezeRing-22]
	_ = x[WeaponSaber10-23]
	_ = x[WeaponToxicAxe-24]
	_ = x[WeaponFlexScarf-25]
	_ = x[WeaponBlackShard-26]
}

const _Weapon_name = "EmptyWoodBladeManeAxRedScarfEverybodyWeaponSpookyswordBraveAxDevilsknifeTrefoilRaggerDaintyScarfTwistedSwdSnowRingThornRingBounceBladeCheerScarfMechaSaberAutoAxeFiberScarfRagger2BrokenSwdPuppetScarfFreezeRingSaber10ToxicAxeFlexScarfBlackShard"

var _Weapon_index = [...]uint8{0, 5, 14, 20, 28, 43, 54, 61, 72, 79, 85, 96, 106, 114, 123, 134, 144, 154, 161, 171, 178, 187, 198, 208, 215, 223, 232, 242}

func (i Weapon) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Weapon_index)-1 {
		return "Weapon(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Weapon_name[_Weapon_index[idx]:_Weapon_index[idx+1]]
}
