// Code generated by "stringer -type=Weapon -trimprefix=Weapon"; DO NOT EDIT.

package saves

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponEmpty-0]
	_ = x[WeaponWoodBlade-1]
	_ = x[WeaponManeAx-2]
	_ = x[WeaponRedScarf-3]
	_ = x[WeaponEverybodyWeapon-4]
	_ = x[WeaponSpookysword-5]
	_ = x[WeaponBraveAx-6]
	_ = x[WeaponDevilsknife-7]
	_ = x[WeaponTrefoil-8]
	_ = x[WeaponRagger-9]
	_ = x[WeaponDaintyScarf-10]
	_ = x[WeaponTwistedSwd-11]
	_ = x[WeaponSnowRing-12]
	_ = x[WeaponThornRing-13]
	_ = x[WeaponBounceBlade-14]
	_ = x[WeaponCheerScarf-15]
	_ = x[WeaponMechaSaber-16]
	_ = x[WeaponAutoAxe-17]
	_ = x[WeaponFiberScarf-18]
	_ = x[WeaponRagger2-19]
	_ = x[WeaponBrokenSwd-20]
	_ = x[WeaponPuppetScarf-21]
	_ = x[WeaponFreezeRing-22]
	_ = x[WeaponSaber10-23]
	_ = x[WeaponToxicAxe-24]
	_ = x[WeaponFlexScarf-25]
	_ = x[WeaponBlackShard-26]
	_ = x[WeaponWoodBlade2-30]
	_ = x[WeaponThatchet-31]
	_ = x[WeaponBlueShoes-32]
	_ = x[WeaponAquaKnife-33]
	_ = x[WeaponFloweryScarf-34]
	_ = x[WeaponBrokenScarf-35]
	_ = x[WeaponGildedRose-36]
	_ = x[WeaponMistleWP-37]
	_ = x[WeaponJingleBlade-50]
	_ = x[WeaponScarfMark-51]
	_ = x[WeaponJusticeAxe-52]
	_ = x[WeaponWinglade-53]
	_ = x[WeaponAbsorbAx-54]
}

const (
	_Weapon_name_0 = "EmptyWoodBladeManeAxRedScarfEverybodyWeaponSpookyswordBraveAxDevilsknifeTrefoilRaggerDaintyScarfTwistedSwdSnowRingThornRingBounceBladeCheerScarfMechaSaberAutoAxeFiberScarfRagger2BrokenSwdPuppetScarfFreezeRingSaber10ToxicAxeFlexScarfBlackShard"
	_Weapon_name_1 = "WoodBlade2ThatchetBlueShoesAquaKnifeFloweryScarfBrokenScarfGildedRoseMistleWP"
	_Weapon_name_2 = "JingleBladeScarfMarkJusticeAxeWingladeAbsorbAx"
)

var (
	_Weapon_index_0 = [...]uint8{0, 5, 14, 20, 28, 43, 54, 61, 72, 79, 85, 96, 106, 114, 123, 134, 144, 154, 161, 171, 178, 187, 198, 208, 215, 223, 232, 242}
	_Weapon_index_1 = [...]uint8{0, 10, 18, 27, 36, 48, 59, 69, 77}
	_Weapon_index_2 = [...]uint8{0, 11, 20, 30, 38, 46}
)

func (i Weapon) String() string {
	switch {
	case 0 <= i && i <= 26:
		return _Weapon_name_0[_Weapon_index_0[i]:_Weapon_index_0[i+1]]
	case 30 <= i && i <= 37:
		i -= 30
		return _Weapon_name_1[_Weapon_index_1[i]:_Weapon_index_1[i+1]]
	case 50 <= i && i <= 54:
		i -= 50
		return _Weapon_name_2[_Weapon_index_2[i]:_Weapon_index_2[i+1]]
	default:
		return "Weapon(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
